<?php
namespace Ktran\CE;

use Illuminate\Support\ServiceProvider;

class CEServiceProvider extends ServiceProvider
{
    public function boot(){
        if (file_exists(__DIR__ . '/helpers.php')) {
            require __DIR__ . '/helpers.php';
        }
        $this->loadRoutesFrom(__DIR__.'/routes.php');
        $this->loadViewsFrom(__DIR__.'/Views', 'ce');
        $this->loadMigrationsFrom(__DIR__.'/Migrations');

        $this->publishes([
            __DIR__.'/assets/' => public_path('vendor/ktran/ckeditor-elfinder'),
        ], 'public');
        $this->publishes([
            __DIR__.'/Configs/ckeditor_elfinder.php' => config_path('ckeditor_elfinder.php'),
        ]);


    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
